//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace edzzn.DB
{
	/// <summary>
	/// DomainModel DBDomainModel
	/// Description for edzzn.DB.DB
	/// </summary>
	[DslDesign::DisplayNameResource("edzzn.DB.DBDomainModel.DisplayName", typeof(global::edzzn.DB.DBDomainModel), "edzzn.DB.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("edzzn.DB.DBDomainModel.Description", typeof(global::edzzn.DB.DBDomainModel), "edzzn.DB.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("8c4206b3-08e7-46f4-843b-182baa92ea1f")]
	public partial class DBDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// DBDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x8c4206b3, 0x08e7, 0x46f4, 0x84, 0x3b, 0x18, 0x2b, 0xaa, 0x92, 0xea, 0x1f);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public DBDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(DBModel),
				typeof(ExampleElement),
				typeof(Tabla),
				typeof(Vista),
				typeof(ProcedimientoAlmacenado),
				typeof(Campo),
				typeof(ClavePrimaria),
				typeof(Relacion),
				typeof(Trigger),
				typeof(Evento),
				typeof(ExampleModelHasElements),
				typeof(ExampleElementReferencesTargets),
				typeof(DBModelTieneTabla),
				typeof(DBModelTieneVista),
				typeof(DBModelTieneProcedimientoAlmacenado),
				typeof(TablaTieneCampo),
				typeof(TablaTieneClavePrimaria),
				typeof(DBModelTieneRelacion),
				typeof(RelacionReferenciasTabla),
				typeof(TriggerTieneEvento),
				typeof(TriggerReferenciasTabla),
				typeof(DBModelTieneTrigger),
				typeof(DBDiagram),
				typeof(ExampleConnector),
				typeof(RelacionTablaConnector),
				typeof(TriggerReferencesTableConnector),
				typeof(ExampleShape),
				typeof(TablaShape),
				typeof(ProcedimientoAlmacenadoShape),
				typeof(VistaShape),
				typeof(RelacionShape),
				typeof(EventoShape),
				typeof(TablaCompartmentShape),
				typeof(TriggerCompartmentShape),
				typeof(global::edzzn.DB.FixUpDiagram),
				typeof(global::edzzn.DB.ConnectorRolePlayerChanged),
				typeof(global::edzzn.DB.CompartmentItemAddRule),
				typeof(global::edzzn.DB.CompartmentItemDeleteRule),
				typeof(global::edzzn.DB.CompartmentItemRolePlayerChangeRule),
				typeof(global::edzzn.DB.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::edzzn.DB.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(ExampleElement), "Name", ExampleElement.NameDomainPropertyId, typeof(ExampleElement.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Tabla), "Nombre", Tabla.NombreDomainPropertyId, typeof(Tabla.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Vista), "Name", Vista.NameDomainPropertyId, typeof(Vista.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Vista), "SqlQuery", Vista.SqlQueryDomainPropertyId, typeof(Vista.SqlQueryPropertyHandler)),
				new DomainMemberInfo(typeof(ProcedimientoAlmacenado), "Nombre", ProcedimientoAlmacenado.NombreDomainPropertyId, typeof(ProcedimientoAlmacenado.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(ProcedimientoAlmacenado), "SqlQuery", ProcedimientoAlmacenado.SqlQueryDomainPropertyId, typeof(ProcedimientoAlmacenado.SqlQueryPropertyHandler)),
				new DomainMemberInfo(typeof(Campo), "Nombre", Campo.NombreDomainPropertyId, typeof(Campo.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Campo), "Valor", Campo.ValorDomainPropertyId, typeof(Campo.ValorPropertyHandler)),
				new DomainMemberInfo(typeof(Campo), "Tipo", Campo.TipoDomainPropertyId, typeof(Campo.TipoPropertyHandler)),
				new DomainMemberInfo(typeof(ClavePrimaria), "Nombre", ClavePrimaria.NombreDomainPropertyId, typeof(ClavePrimaria.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "Nombre", Relacion.NombreDomainPropertyId, typeof(Relacion.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Trigger), "Nombre", Trigger.NombreDomainPropertyId, typeof(Trigger.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Trigger), "SQL", Trigger.SQLDomainPropertyId, typeof(Trigger.SQLPropertyHandler)),
				new DomainMemberInfo(typeof(Evento), "Nombre", Evento.NombreDomainPropertyId, typeof(Evento.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Evento), "Tipo", Evento.TipoDomainPropertyId, typeof(Evento.TipoPropertyHandler)),
				new DomainMemberInfo(typeof(TablaCompartmentShape), "Nombre", TablaCompartmentShape.NombreDomainPropertyId, typeof(TablaCompartmentShape.NombrePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(ExampleModelHasElements), "DBModel", ExampleModelHasElements.DBModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ExampleModelHasElements), "Element", ExampleModelHasElements.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(ExampleElementReferencesTargets), "Source", ExampleElementReferencesTargets.SourceDomainRoleId),
				new DomainRolePlayerInfo(typeof(ExampleElementReferencesTargets), "Target", ExampleElementReferencesTargets.TargetDomainRoleId),
				new DomainRolePlayerInfo(typeof(DBModelTieneTabla), "DBModel", DBModelTieneTabla.DBModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(DBModelTieneTabla), "Tabla", DBModelTieneTabla.TablaDomainRoleId),
				new DomainRolePlayerInfo(typeof(DBModelTieneVista), "DBModel", DBModelTieneVista.DBModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(DBModelTieneVista), "Vista", DBModelTieneVista.VistaDomainRoleId),
				new DomainRolePlayerInfo(typeof(DBModelTieneProcedimientoAlmacenado), "DBModel", DBModelTieneProcedimientoAlmacenado.DBModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(DBModelTieneProcedimientoAlmacenado), "ProcedimientoAlmacenado", DBModelTieneProcedimientoAlmacenado.ProcedimientoAlmacenadoDomainRoleId),
				new DomainRolePlayerInfo(typeof(TablaTieneCampo), "Tabla", TablaTieneCampo.TablaDomainRoleId),
				new DomainRolePlayerInfo(typeof(TablaTieneCampo), "Campo", TablaTieneCampo.CampoDomainRoleId),
				new DomainRolePlayerInfo(typeof(TablaTieneClavePrimaria), "Tabla", TablaTieneClavePrimaria.TablaDomainRoleId),
				new DomainRolePlayerInfo(typeof(TablaTieneClavePrimaria), "ClavePrimaria", TablaTieneClavePrimaria.ClavePrimariaDomainRoleId),
				new DomainRolePlayerInfo(typeof(DBModelTieneRelacion), "DBModel", DBModelTieneRelacion.DBModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(DBModelTieneRelacion), "Relacion", DBModelTieneRelacion.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferenciasTabla), "Relacion", RelacionReferenciasTabla.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferenciasTabla), "Tabla", RelacionReferenciasTabla.TablaDomainRoleId),
				new DomainRolePlayerInfo(typeof(TriggerTieneEvento), "Trigger", TriggerTieneEvento.TriggerDomainRoleId),
				new DomainRolePlayerInfo(typeof(TriggerTieneEvento), "Evento", TriggerTieneEvento.EventoDomainRoleId),
				new DomainRolePlayerInfo(typeof(TriggerReferenciasTabla), "Trigger", TriggerReferenciasTabla.TriggerDomainRoleId),
				new DomainRolePlayerInfo(typeof(TriggerReferenciasTabla), "Tabla", TriggerReferenciasTabla.TablaDomainRoleId),
				new DomainRolePlayerInfo(typeof(DBModelTieneTrigger), "DBModel", DBModelTieneTrigger.DBModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(DBModelTieneTrigger), "Trigger", DBModelTieneTrigger.TriggerDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(22);
				createElementMap.Add(typeof(DBModel), 0);
				createElementMap.Add(typeof(ExampleElement), 1);
				createElementMap.Add(typeof(Tabla), 2);
				createElementMap.Add(typeof(Vista), 3);
				createElementMap.Add(typeof(ProcedimientoAlmacenado), 4);
				createElementMap.Add(typeof(Campo), 5);
				createElementMap.Add(typeof(ClavePrimaria), 6);
				createElementMap.Add(typeof(Relacion), 7);
				createElementMap.Add(typeof(Trigger), 8);
				createElementMap.Add(typeof(Evento), 9);
				createElementMap.Add(typeof(DBDiagram), 10);
				createElementMap.Add(typeof(ExampleConnector), 11);
				createElementMap.Add(typeof(RelacionTablaConnector), 12);
				createElementMap.Add(typeof(TriggerReferencesTableConnector), 13);
				createElementMap.Add(typeof(ExampleShape), 14);
				createElementMap.Add(typeof(TablaShape), 15);
				createElementMap.Add(typeof(ProcedimientoAlmacenadoShape), 16);
				createElementMap.Add(typeof(VistaShape), 17);
				createElementMap.Add(typeof(RelacionShape), 18);
				createElementMap.Add(typeof(EventoShape), 19);
				createElementMap.Add(typeof(TablaCompartmentShape), 20);
				createElementMap.Add(typeof(TriggerCompartmentShape), 21);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::edzzn.DB.DBDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new DBModel(partition, propertyAssignments);
				case 1: return new ExampleElement(partition, propertyAssignments);
				case 2: return new Tabla(partition, propertyAssignments);
				case 3: return new Vista(partition, propertyAssignments);
				case 4: return new ProcedimientoAlmacenado(partition, propertyAssignments);
				case 5: return new Campo(partition, propertyAssignments);
				case 6: return new ClavePrimaria(partition, propertyAssignments);
				case 7: return new Relacion(partition, propertyAssignments);
				case 8: return new Trigger(partition, propertyAssignments);
				case 9: return new Evento(partition, propertyAssignments);
				case 10: return new DBDiagram(partition, propertyAssignments);
				case 11: return new ExampleConnector(partition, propertyAssignments);
				case 12: return new RelacionTablaConnector(partition, propertyAssignments);
				case 13: return new TriggerReferencesTableConnector(partition, propertyAssignments);
				case 14: return new ExampleShape(partition, propertyAssignments);
				case 15: return new TablaShape(partition, propertyAssignments);
				case 16: return new ProcedimientoAlmacenadoShape(partition, propertyAssignments);
				case 17: return new VistaShape(partition, propertyAssignments);
				case 18: return new RelacionShape(partition, propertyAssignments);
				case 19: return new EventoShape(partition, propertyAssignments);
				case 20: return new TablaCompartmentShape(partition, propertyAssignments);
				case 21: return new TriggerCompartmentShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(12);
				createElementLinkMap.Add(typeof(ExampleModelHasElements), 0);
				createElementLinkMap.Add(typeof(ExampleElementReferencesTargets), 1);
				createElementLinkMap.Add(typeof(DBModelTieneTabla), 2);
				createElementLinkMap.Add(typeof(DBModelTieneVista), 3);
				createElementLinkMap.Add(typeof(DBModelTieneProcedimientoAlmacenado), 4);
				createElementLinkMap.Add(typeof(TablaTieneCampo), 5);
				createElementLinkMap.Add(typeof(TablaTieneClavePrimaria), 6);
				createElementLinkMap.Add(typeof(DBModelTieneRelacion), 7);
				createElementLinkMap.Add(typeof(RelacionReferenciasTabla), 8);
				createElementLinkMap.Add(typeof(TriggerTieneEvento), 9);
				createElementLinkMap.Add(typeof(TriggerReferenciasTabla), 10);
				createElementLinkMap.Add(typeof(DBModelTieneTrigger), 11);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::edzzn.DB.DBDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new ExampleModelHasElements(partition, roleAssignments, propertyAssignments);
				case 1: return new ExampleElementReferencesTargets(partition, roleAssignments, propertyAssignments);
				case 2: return new DBModelTieneTabla(partition, roleAssignments, propertyAssignments);
				case 3: return new DBModelTieneVista(partition, roleAssignments, propertyAssignments);
				case 4: return new DBModelTieneProcedimientoAlmacenado(partition, roleAssignments, propertyAssignments);
				case 5: return new TablaTieneCampo(partition, roleAssignments, propertyAssignments);
				case 6: return new TablaTieneClavePrimaria(partition, roleAssignments, propertyAssignments);
				case 7: return new DBModelTieneRelacion(partition, roleAssignments, propertyAssignments);
				case 8: return new RelacionReferenciasTabla(partition, roleAssignments, propertyAssignments);
				case 9: return new TriggerTieneEvento(partition, roleAssignments, propertyAssignments);
				case 10: return new TriggerReferenciasTabla(partition, roleAssignments, propertyAssignments);
				case 11: return new DBModelTieneTrigger(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "edzzn.DB.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DBDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (DBDomainModel.resourceManager == null)
				{
					DBDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(DBDomainModel).Assembly);
				}
				return DBDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return DBDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return DBDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DBDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new DBCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					DBDomainModel.copyClosure = copyFilter;
				}
				return DBDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DBDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new DBDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					DBDomainModel.removeClosure = removeFilter;
				}
				return DBDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::edzzn.DB.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::edzzn.DB.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::edzzn.DB.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::edzzn.DB.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::edzzn.DB.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::edzzn.DB.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::edzzn.DB.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::edzzn.DB.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::edzzn.DB.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::edzzn.DB.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::edzzn.DB.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::edzzn.DB.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::edzzn.DB.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::edzzn.DB.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DBDeleteClosure : DBDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DBDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DBDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public DBDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::edzzn.DB.ExampleModelHasElements.ElementDomainRoleId, true);
			DomainRoles.Add(global::edzzn.DB.DBModelTieneTabla.TablaDomainRoleId, true);
			DomainRoles.Add(global::edzzn.DB.DBModelTieneVista.VistaDomainRoleId, true);
			DomainRoles.Add(global::edzzn.DB.DBModelTieneProcedimientoAlmacenado.ProcedimientoAlmacenadoDomainRoleId, true);
			DomainRoles.Add(global::edzzn.DB.TablaTieneCampo.CampoDomainRoleId, true);
			DomainRoles.Add(global::edzzn.DB.TablaTieneClavePrimaria.ClavePrimariaDomainRoleId, true);
			DomainRoles.Add(global::edzzn.DB.DBModelTieneRelacion.RelacionDomainRoleId, true);
			DomainRoles.Add(global::edzzn.DB.TriggerTieneEvento.EventoDomainRoleId, true);
			DomainRoles.Add(global::edzzn.DB.DBModelTieneTrigger.TriggerDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DBCopyClosure : DBCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DBCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DBCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DBCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

