//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edzzn.DB
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DB";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DB";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"edzzn";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DBDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DBCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DBExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DBCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDBExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DBCommandSetId), 0x0001);
	
		// Package identifier
		public const string DBPackageId = "177dfacf-a979-4a1e-a52f-a81d23df543f";
		
		// Editor factory identifier
		public const string DBEditorFactoryId = "67b27b86-d3c0-460c-a1b7-0a530d75cf00";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DBModelExplorerToolWindowId = "f88da6f1-0cf2-483b-bcd3-fd9dd0495def";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace edzzn.DB
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DBCommandSetId = "3660a3d2-5836-4ec0-990e-7ff0bcce9f4f";
	}
}